name: Deploy backend to staging in heroku
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: 'Cache Yarn dependencies'
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: 'Installing dependencies'
      run: cd backend && yarn install
    - name: 'Building the build'
      run: cd backend && yarn build
    - name: 'Deploy to heroku'
      uses: akhileshns/heroku-deploy@v3.0.5      
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "staging-ytmdown" 
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "backend"
